name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.x

    - name: Build via Bash
      if: runner.os != 'Windows'
      run: ./build.sh
      env:
        CI: true
        CONFIGURATION: ${{ matrix.configuration }}
        ENABLE_COVERAGE: true

    - name: Build via Windows
      if: runner.os == 'Windows'
      run: ./build.cmd
      env:
        CI: true
        CONFIGURATION: ${{ matrix.configuration }}
        ENABLE_COVERAGE: true
